#!/usr/bin/bash
SCRIPT_DIR=$(cd $(dirname $BASH_SOURCE[0]) > /dev/null; pwd)
cd $SCRIPT_DIR
REPO_DIR="$HOME/repos/ghostty"
REPO_URL="https://github.com/ghostty-org/ghostty"

# if debian based ensure you have following dependancies
if [ -f /etc/debian_version ]; then
  if [ ! -d $REPO_DIR ]; then
    echo "Did not detect previous setup ... installing debian dependancies"
    echo "sudo apt install libgtk-4-dev libadwaita-1-dev git \ " 
    echo "                 libncurses-dev blueprint-compiler"
    sleep 1

    sudo apt update && sudo apt install libgtk-4-dev libadwaita-1-dev \
                                git libncurses-dev blueprint-compiler 

    if [ $? -eq 0 ]; then
      echo "Success: dependancies installed"
      sleep 1
    else
      echo "Error: Unable to install dependancies"
      echo "       ... continuing on but recommend revisiting/debugging"
      sleep 3
    fi
  fi
fi

if ! command -v zig > /dev/null; then 
  echo "Error: Missing zig"
  echo "   hint: ~/.bash.d/zig.sh"
  exit 1
fi

ZIG_VERSION_NEEDED="0.14.0"
ZIG_VERSION=`zig version`
if [ "$ZIG_VERSION" != "$ZIG_VERSION_NEEDED" ]; then
  echo "Error zig version not right."
  echo "    Want: $ZIG_VERSION_NEEDED  Have: $ZIG_VERSION"
  echo ""
  exit 1
fi

if [ ! -d $REPO_DIR ]; then
  echo "Missing ghostty checkout: $REPO_DIR"
  mkdir -p $(dirname $REPO_DIR)
  cd $(dirname $REPO_DIR)
  echo "Cloning $REPO_URL into $REPO_DIR"
  if git clone $REPO_URL; then
    echo "Cloned ghostty into: $HOME/repos/ghostty"
  else
    echo "Failed to clone ghostty into: $HOME/repos/ghostty"
    exit 1
  fi
else
  echo "Found ghostty repo: $HOME/repos/ghostty"
fi

cd $HOME/repos/ghostty

echo -n "Doing git pull: "
if ! git pull; then
  echo "Failed git pull .. debug that"
  exit 1
fi

CMD="zig build -p $HOME/.local -Doptimize=ReleaseFast"
echo "Running: $CMD"
sleep 0.2
${CMD}
if [ $? -eq 0 ]; then
  echo "Build successful .. restart / launch your ghostty"
else
  echo "Build failed ... :("
  exit 1
fi
