#!/usr/bin/bash
# Dayne Broderson 2025
# 
# SOURCE_URL="https://ziglang.org/download/0.13.0/zig-0.13.0.tar.xz"
ZIG_VERSION="0.14.0"
ZIG_URL="https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz"
ZIG_DL_FILE="$(basename $ZIG_URL)"
ZIG_DIR="$(basename $ZIG_DL_FILE .tar.xz)"

if command -v zig > /dev/null; then  
  echo -n "Zig found: "
  CURRENT_ZIG_VERSION=`zig version`
  if [ "$CURRENT_ZIG_VERSION" != "$ZIG_VERSION" ]; then
    echo "Not target version: Want: $ZIG_VERSION  Have: $CURRENT_ZIG_VERSION"
  else
    echo "matches target version: $ZIG_VERSION"
    echo "Skipping install"
    exit 0
  fi
else
  echo "No zig found ... attempting install"
fi
sleep 1

if [ ! -d ~/.local/share/zig ]; then
  if ! mkdir -p ~/.local/share/zig; then
    echo "failed to make ~/.local/share/zig"
    exit 1
  fi
fi

cd ~/.local/share/zig
if [ ! -f ${ZIG_DL_FILE}.ready ]; then
  echo "Downloading zig from: $ZIG_URL"
  if [ -f ${ZIG_DL_FILE}.temp ]; then
    echo "Detected partial download - removing: ${ZIG_DL_FILE}.temp"
    rm ${ZIG_DL_FILE}.temp
  fi
  if ! wget  -O ${ZIG_DL_FILE}.temp -q $ZIG_URL; then
    echo "Error: Download failed!"
    exit 1
  else
    echo "Success: Downloaded $ZIG_DL_FILE"
    mv ${ZIG_DL_FILE}.temp ${ZIG_DL_FILE}
    touch ${ZIG_DL_FILE}.ready
  fi
  sleep 1
fi

if [ ! -f $ZIG_DIR ]; then
  if tar xf $ZIG_DL_FILE; then 
    echo "Extracted $ZIG_DL_FILE"
  else
    echo "Failed: tar xf $ZIG_DL_FILE"
    exit 1
  fi
  sleep 1
fi

if ln -sf $HOME/.local/share/zig/$ZIG_DIR/zig $HOME/.local/bin/zig; then
  echo "Created symbolink link ~/.local/bin/zig"
else
  echo "Failed to create sym link from $HOME/.local/share/zig/$ZIG_DIR/zig"
  echo "    into $HOME/.local/bin/zig"
  exit 1
fi
